// Shared location lists (kept separate from Hero to avoid pulling the hero bundle into forms/list pages).

export const cities = [
  "Islamabad",
  "Rawalpindi",
  "Haripur",
  "Abbottabad",
  "Hawlian",
  "Khanpur",
];
export const areasByCity: Record<string, string[]> = {
  Islamabad: [
    "F-5",
    "F-6",
    "F-7",
    "F-8",
    "F-10",
    "F-11",
    "F-12",
    "F-13",
    "F-14",
    "F-15",
    "F-16",
    "F-17",
    "G-5",
    "G-6",
    "G-7",
    "G-8",
    "G-9",
    "G-10",
    "G-11",
    "G-12",
    "G-13",
    "G-14",
    "G-15",
    "G-16",
    "I-8",
    "I-9",
    "I-10",
    "I-11",
    "I-12",
    "I-14",
    "I-15",
    "I-16",
    "H-8",
    "H-9",
    "H-10",
    "H-11",
    "H-12",
    "H-13",
    "H-14",
    "H-15",
    "H-16",
    "E-7",
    "E-8",
    "E-9",
    "E-10",
    "E-11",
    "E-12",
    "E-13",
    "E-14",
    "E-15",
    "E-16",
    "E-17",
    "D-12",
    "D-13",
    "D-14",
    "D-15",
    "D-16",
    "D-17",
    "C-13",
    "C-14",
    "C-15",
    "C-16",
    "DHA Phase 1",
    "DHA Phase 2",
    "DHA Phase 3",
    "DHA Phase 4",
    "DHA Phase 5",
    "Bahria Town Phase 1",
    "Bahria Town Phase 2",
    "Bahria Town Phase 3",
    "Bahria Town Phase 4",
    "Bahria Town Phase 5",
    "Bahria Town Phase 6",
    "Bahria Town Phase 7",
    "Bahria Town Phase 8",
    "Safari Valley",
    "Gulberg Greens",
    "Gulberg Residencia",
    "B-17 (Multi Gardens)",
    "Top City-1",
    "Park View City",
    "Capital Smart City",
    "Faisal Town",
    "Faisal Hills",
    "PECHS",
    "Naval Anchorage",
    "PWD Housing Society",
    "Soan Garden",
    "Media Town",
    "Pakistan Town",
    "Korang Town",
    "River Garden",
    "Engineers Cooperative Housing",
    "Police Foundation",
    "FGEHA Sectors",
    "Khanna Pul",
    "Burma Town",
    "Tarnol",
    "Alipur Farash",
    "Tramari",
    "Tarlai",
    "Sihala",
    "Nilore",
    "Lehtrar Road",
    "Bhara Kahu",
    "Bani Gala",
    "Shah Allah Ditta",
    "Golra",
    "Sangjani",
    "Model Town Humak",
    "Rawat",
    "Kahuta Road Belt",
    "Blue Area",
    "Aabpara",
    "Melody Market",
    "G-9 Markaz",
    "F-10 Markaz",
    "F-7 Jinnah Super",
    "I-8 Markaz",
    "G-11 Markaz",
  ],
  Rawalpindi: [
    "Afandi Colony",
    "AFOHS Falcon Complex",
    "Amarpura",
    "Arya Mohallah",
    "Asghar Mall",
    "Badar Colony",
    "Banni",
    "Chah Sultan",
    "Chamanzaar Colony",
    "Chaudhry Waris Khan",
    "Chhachhi",
    "Choudhry Feroz",
    "Dhok Elahi Bakhsh",
    "Dhok Kala Khan",
    "Dhok Khabba",
    "Dhoke Ali Akbar",
    "Dhoke Babu Irfan",
    "Dhoke Bajalian",
    "Dhoke Hassu",
    "Dhoke Hukamdad",
    "Dhoke Jattan",
    "Faizabad",
    "Fazaia Colony",
    "Gawalmandi",
    "Gulshanabad",
    "Khayaban-e-Sir Syed",
    "Khurram Colony",
    "Mall Road",
    "Millat Colony",
    "Mohanpura",
    "Muslim Town",
    "New Katarian",
    "Noshahi",
    "Nussah Town",
    "Old City",
    "Peshawar Road",
    "Pindora",
    "Pirwadhai",
    "Qayyum Abad",
    "Raja Bazaar",
    "Rasul Nagar",
    "Ratta Amral",
    "Roshan Din",
    "Sadiqabad",
    "Saddar",
    "Sangar Town",
    "Satellite Town (All Blocks)",
    "Shaheen Town (Phase I & II)",
    "Shakrial",
    "Shamsabad",
    "Sharifpura",
    "Shifa Society",
    "Syed Pur",
    "Tajuddin",
    "Westridge 1",
    "Westridge 2",
    "Westridge 3",
  ],
  Haripur: [
    "Abdullah Pur",
    "Adalat Colony",
    "Akhori",
    "Akhtdrabad",
    "Akhoon Bandi",
    "Ali Khan",
    "Alam",
    "Alloli / Alluli",
    "Amb",
    "Amgah",
    "Anora",
    "Anga",
    "Ashra",
    "Azam Chowk",
    "Aziz Colony",
    "Babu Chowk",
    "Badgiran",
    "Badhora",
    "Bagh",
    "Baghdara",
    "Bail",
    "Bakka",
    "Bandi Sher Khan",
    "Barkot",
    "Beer",
    "Behki",
    "Bhand",
    "Bhuttri",
    "Biralian",
    "Breela",
    "Buraj Khanpur",
    "Chakar Mirpur",
    "Chor / Chhori",
    "Darwesh",
    "Dheri",
    "Dingi",
    "Doyan Abi",
    "Essa",
    "Gadwallian",
    "Ghara / Gharian",
    "Ghazi",
    "Goharabad",
    "Hassanpur",
    "Hattar",
    "Haripur City",
    "Hussaini Chowk",
    "Jabbar",
    "Jatti Pind",
    "Jogi Mohra",
    "Kag",
    "Kalinjar",
    "Kamalpur",
    "Kanera",
    "Khairbara",
    "Khalabat Township",
    "Kholian Bala",
    "Kotla",
    "Kundi",
    "Lalogali",
    "Maira Dheri",
    "Makhniyal",
    "Mankrai",
    "Mirpur",
    "Najafpur",
    "Nara Amaz",
    "Neelan Bhotu",
    "Panian",
    "Pandak",
    "Pind Hasham Khan",
    "Pind Jamal",
    "Pharhari",
    "Qazipur",
    "Rehana",
    "Sarai Saleh",
    "Sangra",
    "Sirikot",
    "Sobra",
    "Tarbela",
    "Tofkian",
    "Umer Khana",
    "Khala Bala",
    "Khomal Paien",
  ],
  Abbottabad: [
    "Abbottabad City",
    "Kehal",
    "Jhangi",
    "Malikpura",
    "Nawansher",
    "Supply",
    "Mandian",
    "Sheikh-ul-Bandi",
    "Bagnotar",
    "Bakot",
    "Bandi Qazi",
    "Bandi Dhundan",
    "Beerangali",
    "Berot Khurd",
    "Boi",
    "Chamhad",
    "Chatri",
    "Dhamtour",
    "Jarral",
    "Kakul",
    "Kuthiala",
    "Kuthwal",
    "Lora",
    "Namli Maira",
    "Nathia Gali",
    "Pawa",
    "Phalkot",
    "Pind Kargu Khan",
    "Salhad",
    "Sarbhana",
    "Sherwan",
    "Tarnawai",
    "Tajwal",
    "Thathi Faqir Sahib",
    "Nagri Bala",
    "Mirpur",
    "Bagh",
    "Baldheri",
    "Havelian City",
    "Bandi Attai Khan",
    "Dewal Manal",
    "Garhi Phulgran",
    "Goreeni",
    "Jhangra",
    "Langra",
    "Langrial",
    "Majuhan",
    "Nara",
  ],
  Hawlian: ["City Area", "College Road", "Main Bazaar"],
  Khanpur: ["Khanpur City", "Bhamala", "Dam Side"],
};
